version: '3.8'

services:
  c-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: c-lang
    volumes:
      - ..:/app
    working_dir: /app
    tty: true
    command: sh -c "chmod +x ./src/run.sh && sleep infinity"